<a href="https://colab.research.google.com/github/senthilp61/google_colab/blob/main/Array_and_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array and Matrix [Arrays and Matrices will be introduced by the professor in the following lectures, so let's have a quick look!]

**Array** - An array is a special variable that can hold more than one value at a time. Both the list and array look similar by one major difference is that ana array is optimized for arithmetic computations.

Syntax - **arr = np.array([1,2,3])**


**Matrix** - A Matrix is a 2-Dimensional array. It has both rows and columns. The horizontal arrangement of data is known as **row** and the vertical arrangement of data is known as column.

Syntax - **mat = np.array([[1, 2, 3, 1], [4, 5, 6, 4], [7, 8, 9, 7]])**

The above code will create a matrix (mat) with 3 rows and 4 columns

In [ ]:
# The first step of using numpy is to tell python to import it
import numpy as np

In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
mat = np.array([[1,2,3,1],[4,5,6,4],[7,8,9,7]])
mat

array([[1, 2, 3, 1],
       [4, 5, 6, 4],
       [7, 8, 9, 7]])

## 2.1 NumPy Arrays

**NumPy Array**
*   An array is a data structure that stores values of same data type.
*   While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to the same data type.
*   However python lists fail to deliver the performance required while computing large sets of numerical data. To address this issue we use NumPy arrays.
*   We can create NumPy arrays by converting a list to an array.





In [ ]:
# defining a list of different car companies or string elements
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

#defining a list of number of cylinders in car or numerical elements
arr_num = [5, 4, 6, 7, 3]

In [ ]:
#converting the list arr_str to a NumPy array
np_arr_str = np.array(arr_str)

#converting the list arr_num to a NumPy array
np_arr_num = np.array(arr_num)

# checking the output
print("NumPy Array (arr_str): ", np_arr_str)
print("NumPy Array (arr_num):", np_arr_num)

NumPy Array (arr_str):  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
NumPy Array (arr_num): [5 4 6 7 3]


The result look similar to a list but arr_str and arr_num have been converted to NumPy arrays. Let's check the data type to confirm this.

In [ ]:
# printing the data type of lists
print("Data type of arr_str: ", type(arr_str))
print("Data type of arr_num: ", type(arr_num))

# printing the data types after conversion of lists to array
print("Data type of np_arr_str: ", type(np_arr_str))
print("Data type of np_arr_str: ", type(np_arr_num))

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>
Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_str:  <class 'numpy.ndarray'>




*   The above output confirms that both the lists were successfully converted to arrays

**NumPy Matrix**


*   A matrix is a two-dimensional data structure where elements are arranged into rows and columns.
*   A matrix can be created by using list of lists





In [ ]:
# matrix

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Data type of matrix: ", type(mat))
mat

Data type of matrix:  <class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])



*   We see that all the NumPy objects have data type as ndarray



## 2.2 NumPy Functions

**There are different ways to create NumPy arrays using the functions available in NumPy library**

**Using np.arange() function**


*   The np.arange() function returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. start is included but stop is excluded.
*   It has the following parameters:


*   **start**: start of interval range. By default start = 0
*   **stop**: end of interval range


*   **step**: step size of interval. By default step size = 1







In [ ]:
arr2 = np.arange(start=0, stop=10) # 10 will be excluded from the output
print(arr2)

# or

arr2 = np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# adding a step size of 5 to create an array
arr3 = np.arange(start = 0, stop = 20, step = 5)
arr3

array([ 0,  5, 10, 15])

**Using np.linspace() function**


*   The np.linspace() function returns numbers which are evenly distributed with respect to interval. Here the start and stop both are included.
*   It has the following parameters:


*   start: start of interval range. By default start = 0
*   stop: end of interval range.


*   num: No. of samples to generate. By default num = 50







In [ ]:
arr4 = np.linspace(start=0, stop=10, num=5, endpoint=False) # default num=50 & endpoint=True
arr4

# or

arr4 = np.linspace(0,10,5, endpoint=False)
arr4

arr5 = np.linspace(0,10)
arr5

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**How are these values getting generated?**

The step size or the difference between each element will be decidied by the following formula:

**(stop-start)/ (total elements -1)**

So, in this case: (5-0) / 49 = 0.10204082

The first value will be 0.10204082, the second value will be 0.10204082 + 0.10204082 and so on.

In [ ]:
# generating 10 evenly spaced values between 10 and 20
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

**Similarly we can create matrices using the functions available in NumPy library**

**Using np.zeros()**


*   The np.zeros() is a function for creating a matrix and performing matrix operations in NumPy.
*   It returns a matrix filled with zeros of the given shape.


*   It has the following parameters:
*   **shape**: Number of rows and columns in the output matrix.


*   **dtype**: data type of the elements in the matrix, by default the value is set to float.







In [ ]:
matrix5 = np.zeros([3,5])
matrix5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Using np.ones()
*   The np.ones() is another function for creating a matrix and performing matrix operations in NumPy
*   It returns a matrix of given shape and type, filled with ones.


*   It has the following parameters:
*   **shape**: Number of rows and columns in the output matrix.


*   **dtype**: data type of the elements in the matrix, by default the value is set to float.







In [ ]:
matrix6 = np.ones([3,5])
matrix6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Using np.eye()**
*   The np.eye() is a function for creating a matrix and performing matrix operations in NumPy.
*   It returns a matrix with ones on the diagonal and zeros elsewhere.


*   It has the following parameters:
*   **n**: Number of rows and columns in the output matrix


*   **dtype**: data type of the elements in the matrix, by default the value is set to float







In [ ]:
matrix7 = np.eye(5)
matrix7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**We can also convert a one dimension array to a matrix. This can be done by using reshape method**

In [ ]:
list = [1,2,3,4,5,6,7,8,9,10]
list_arr = np.array(list)
matrix8 = list_arr.reshape([2,5])
matrix8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])