<a href="https://colab.research.google.com/github/senthilp61/google_colab/blob/main/Basic_Mathematical_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

## Some basic mathematical functions

**Logarithmic Functions**


*   Logarithm with base 10 (log**10**)
*   Logarithm with base e (log**e**)
*   Logarithm with base 2 (log**2**)

**Exponential Function:**


*   By definition, exponential function(i.e exp(x)) is the inverse function of natural logarithmic function (i.e. log**e**)
*   For example, exp(2) = e^2 = 7.389 where e ~ 2.718

**Trignometric Functions:**


*   In trignometry, sin, cos and tan are the basic trignometric ratios used to study the relationship between the angles and sides of a right-angled triagle (hypotenuse).

**Mathematical Functions        NumPy Functions**

log10(x)                             numpy.log10()

loge(x)                              numpy.log()

log2(x)                              numpy.log2()

exp(x)                               numpy.exp()

sin(x)                               numpy.sin()

cos(x)                               numpy.cos()

tan(x)                               numpy.tan()









**Trignometric functions**

In [3]:
print("Sine Function: ", np.sin(4))
print("Cosine Function: ", np.cos(4))
print("Tan Function: ", np.tan(4))

Sine Function:  -0.7568024953079282
Cosine Function:  -0.6536436208636119
Tan Function:  1.1578212823495775


In [6]:
arr4 = np.arange(0,10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print("Sine Function: ", np.sin(arr4))
print("Cosine Function: ", np.cos(arr4))
print("Tan Function: ", np.tan(arr4))

Sine Function:  [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
Cosine Function:  [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
Tan Function:  [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


**Exponents and Logarithmic functions**
*   Exponents



In [8]:
np.exp(2)

7.38905609893065

In [9]:
arr5 = np.array([2, 4, 6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

*   Logarithms



In [10]:
# by default numpy takes the base of log as e
np.log(2)

0.6931471805599453

In [11]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [12]:
# log with base 10
np.log10(5)

0.6989700043360189

In [15]:
# log with base 2
np.log2(10)

3.321928094887362